#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CoreDB")]
	public partial class DBmodelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCliente(Cliente instance);
    partial void UpdateCliente(Cliente instance);
    partial void DeleteCliente(Cliente instance);
    partial void InsertCuenta(Cuenta instance);
    partial void UpdateCuenta(Cuenta instance);
    partial void DeleteCuenta(Cuenta instance);
    partial void InsertPrestamo(Prestamo instance);
    partial void UpdatePrestamo(Prestamo instance);
    partial void DeletePrestamo(Prestamo instance);
    #endregion
		
		public DBmodelDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CoreDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBmodelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBmodelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBmodelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBmodelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Cliente> Clientes
		{
			get
			{
				return this.GetTable<Cliente>();
			}
		}
		
		public System.Data.Linq.Table<Cuenta> Cuentas
		{
			get
			{
				return this.GetTable<Cuenta>();
			}
		}
		
		public System.Data.Linq.Table<Movimiento> Movimientos
		{
			get
			{
				return this.GetTable<Movimiento>();
			}
		}
		
		public System.Data.Linq.Table<Prestamo> Prestamos
		{
			get
			{
				return this.GetTable<Prestamo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Clientes")]
	public partial class Cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private string _Ciudad;
		
		private string _Pais;
		
		private string _Direccion;
		
		private string _TelefonoResidencial;
		
		private string _TelefonoCelular;
		
		private System.Nullable<System.DateTime> _FechaCreacion;
		
		private string _Sexo;
		
		private string _CedulaIdentidad;
		
		private EntitySet<Cuenta> _Cuentas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidoChanging(string value);
    partial void OnApellidoChanged();
    partial void OnCiudadChanging(string value);
    partial void OnCiudadChanged();
    partial void OnPaisChanging(string value);
    partial void OnPaisChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnTelefonoResidencialChanging(string value);
    partial void OnTelefonoResidencialChanged();
    partial void OnTelefonoCelularChanging(string value);
    partial void OnTelefonoCelularChanged();
    partial void OnFechaCreacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaCreacionChanged();
    partial void OnSexoChanging(string value);
    partial void OnSexoChanged();
    partial void OnCedulaIdentidadChanging(string value);
    partial void OnCedulaIdentidadChanged();
    #endregion
		
		public Cliente()
		{
			this._Cuentas = new EntitySet<Cuenta>(new Action<Cuenta>(this.attach_Cuentas), new Action<Cuenta>(this.detach_Cuentas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(200)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="NVarChar(200)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this.OnApellidoChanging(value);
					this.SendPropertyChanging();
					this._Apellido = value;
					this.SendPropertyChanged("Apellido");
					this.OnApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ciudad", DbType="NVarChar(200)")]
		public string Ciudad
		{
			get
			{
				return this._Ciudad;
			}
			set
			{
				if ((this._Ciudad != value))
				{
					this.OnCiudadChanging(value);
					this.SendPropertyChanging();
					this._Ciudad = value;
					this.SendPropertyChanged("Ciudad");
					this.OnCiudadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pais", DbType="NVarChar(200)")]
		public string Pais
		{
			get
			{
				return this._Pais;
			}
			set
			{
				if ((this._Pais != value))
				{
					this.OnPaisChanging(value);
					this.SendPropertyChanging();
					this._Pais = value;
					this.SendPropertyChanged("Pais");
					this.OnPaisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="NVarChar(200)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelefonoResidencial", DbType="NVarChar(200)")]
		public string TelefonoResidencial
		{
			get
			{
				return this._TelefonoResidencial;
			}
			set
			{
				if ((this._TelefonoResidencial != value))
				{
					this.OnTelefonoResidencialChanging(value);
					this.SendPropertyChanging();
					this._TelefonoResidencial = value;
					this.SendPropertyChanged("TelefonoResidencial");
					this.OnTelefonoResidencialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelefonoCelular", DbType="NVarChar(200)")]
		public string TelefonoCelular
		{
			get
			{
				return this._TelefonoCelular;
			}
			set
			{
				if ((this._TelefonoCelular != value))
				{
					this.OnTelefonoCelularChanging(value);
					this.SendPropertyChanging();
					this._TelefonoCelular = value;
					this.SendPropertyChanged("TelefonoCelular");
					this.OnTelefonoCelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this.OnFechaCreacionChanging(value);
					this.SendPropertyChanging();
					this._FechaCreacion = value;
					this.SendPropertyChanged("FechaCreacion");
					this.OnFechaCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexo", DbType="NVarChar(1)")]
		public string Sexo
		{
			get
			{
				return this._Sexo;
			}
			set
			{
				if ((this._Sexo != value))
				{
					this.OnSexoChanging(value);
					this.SendPropertyChanging();
					this._Sexo = value;
					this.SendPropertyChanged("Sexo");
					this.OnSexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CedulaIdentidad", DbType="NVarChar(200)")]
		public string CedulaIdentidad
		{
			get
			{
				return this._CedulaIdentidad;
			}
			set
			{
				if ((this._CedulaIdentidad != value))
				{
					this.OnCedulaIdentidadChanging(value);
					this.SendPropertyChanging();
					this._CedulaIdentidad = value;
					this.SendPropertyChanged("CedulaIdentidad");
					this.OnCedulaIdentidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Cuenta", Storage="_Cuentas", ThisKey="ID", OtherKey="IdCuenta")]
		public EntitySet<Cuenta> Cuentas
		{
			get
			{
				return this._Cuentas;
			}
			set
			{
				this._Cuentas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Cuentas(Cuenta entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = this;
		}
		
		private void detach_Cuentas(Cuenta entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cuentas")]
	public partial class Cuenta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _NumeroDeCuenta;
		
		private string _Tipo;
		
		private string _Propietario;
		
		private System.Nullable<double> _Saldo;
		
		private System.Nullable<double> _TasaInteres;
		
		private System.Nullable<int> _IdCuenta;
		
		private EntitySet<Prestamo> _Prestamos;
		
		private EntityRef<Cliente> _Cliente;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNumeroDeCuentaChanging(System.Nullable<int> value);
    partial void OnNumeroDeCuentaChanged();
    partial void OnTipoChanging(string value);
    partial void OnTipoChanged();
    partial void OnPropietarioChanging(string value);
    partial void OnPropietarioChanged();
    partial void OnSaldoChanging(System.Nullable<double> value);
    partial void OnSaldoChanged();
    partial void OnTasaInteresChanging(System.Nullable<double> value);
    partial void OnTasaInteresChanged();
    partial void OnIdCuentaChanging(System.Nullable<int> value);
    partial void OnIdCuentaChanged();
    #endregion
		
		public Cuenta()
		{
			this._Prestamos = new EntitySet<Prestamo>(new Action<Prestamo>(this.attach_Prestamos), new Action<Prestamo>(this.detach_Prestamos));
			this._Cliente = default(EntityRef<Cliente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroDeCuenta", DbType="Int")]
		public System.Nullable<int> NumeroDeCuenta
		{
			get
			{
				return this._NumeroDeCuenta;
			}
			set
			{
				if ((this._NumeroDeCuenta != value))
				{
					this.OnNumeroDeCuentaChanging(value);
					this.SendPropertyChanging();
					this._NumeroDeCuenta = value;
					this.SendPropertyChanged("NumeroDeCuenta");
					this.OnNumeroDeCuentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="NVarChar(50)")]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this.OnTipoChanging(value);
					this.SendPropertyChanging();
					this._Tipo = value;
					this.SendPropertyChanged("Tipo");
					this.OnTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Propietario", DbType="NVarChar(50)")]
		public string Propietario
		{
			get
			{
				return this._Propietario;
			}
			set
			{
				if ((this._Propietario != value))
				{
					this.OnPropietarioChanging(value);
					this.SendPropertyChanging();
					this._Propietario = value;
					this.SendPropertyChanged("Propietario");
					this.OnPropietarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Saldo", DbType="Float")]
		public System.Nullable<double> Saldo
		{
			get
			{
				return this._Saldo;
			}
			set
			{
				if ((this._Saldo != value))
				{
					this.OnSaldoChanging(value);
					this.SendPropertyChanging();
					this._Saldo = value;
					this.SendPropertyChanged("Saldo");
					this.OnSaldoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TasaInteres", DbType="Float")]
		public System.Nullable<double> TasaInteres
		{
			get
			{
				return this._TasaInteres;
			}
			set
			{
				if ((this._TasaInteres != value))
				{
					this.OnTasaInteresChanging(value);
					this.SendPropertyChanging();
					this._TasaInteres = value;
					this.SendPropertyChanged("TasaInteres");
					this.OnTasaInteresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCuenta", DbType="Int")]
		public System.Nullable<int> IdCuenta
		{
			get
			{
				return this._IdCuenta;
			}
			set
			{
				if ((this._IdCuenta != value))
				{
					if (this._Cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdCuentaChanging(value);
					this.SendPropertyChanging();
					this._IdCuenta = value;
					this.SendPropertyChanged("IdCuenta");
					this.OnIdCuentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cuenta_Prestamo", Storage="_Prestamos", ThisKey="ID", OtherKey="CuentaRelacionada")]
		public EntitySet<Prestamo> Prestamos
		{
			get
			{
				return this._Prestamos;
			}
			set
			{
				this._Prestamos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Cuenta", Storage="_Cliente", ThisKey="IdCuenta", OtherKey="ID", IsForeignKey=true)]
		public Cliente Cliente
		{
			get
			{
				return this._Cliente.Entity;
			}
			set
			{
				Cliente previousValue = this._Cliente.Entity;
				if (((previousValue != value) 
							|| (this._Cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cliente.Entity = null;
						previousValue.Cuentas.Remove(this);
					}
					this._Cliente.Entity = value;
					if ((value != null))
					{
						value.Cuentas.Add(this);
						this._IdCuenta = value.ID;
					}
					else
					{
						this._IdCuenta = default(Nullable<int>);
					}
					this.SendPropertyChanged("Cliente");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Prestamos(Prestamo entity)
		{
			this.SendPropertyChanging();
			entity.Cuenta = this;
		}
		
		private void detach_Prestamos(Prestamo entity)
		{
			this.SendPropertyChanging();
			entity.Cuenta = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Movimientos")]
	public partial class Movimiento
	{
		
		private System.Nullable<int> _idMovimiento;
		
		private string _tipoMovimiento;
		
		private System.Nullable<double> _Monto;
		
		private System.Nullable<int> _CuentaEmisor;
		
		private System.Nullable<int> _CuentaReceptor;
		
		private System.Nullable<System.DateTime> _TiempoStamp;
		
		private string _debito_credito;
		
		private string _Banco;
		
		public Movimiento()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMovimiento", DbType="Int")]
		public System.Nullable<int> idMovimiento
		{
			get
			{
				return this._idMovimiento;
			}
			set
			{
				if ((this._idMovimiento != value))
				{
					this._idMovimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipoMovimiento", DbType="NChar(50)")]
		public string tipoMovimiento
		{
			get
			{
				return this._tipoMovimiento;
			}
			set
			{
				if ((this._tipoMovimiento != value))
				{
					this._tipoMovimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Monto", DbType="Float")]
		public System.Nullable<double> Monto
		{
			get
			{
				return this._Monto;
			}
			set
			{
				if ((this._Monto != value))
				{
					this._Monto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuentaEmisor", DbType="Int")]
		public System.Nullable<int> CuentaEmisor
		{
			get
			{
				return this._CuentaEmisor;
			}
			set
			{
				if ((this._CuentaEmisor != value))
				{
					this._CuentaEmisor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuentaReceptor", DbType="Int")]
		public System.Nullable<int> CuentaReceptor
		{
			get
			{
				return this._CuentaReceptor;
			}
			set
			{
				if ((this._CuentaReceptor != value))
				{
					this._CuentaReceptor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TiempoStamp", DbType="Date")]
		public System.Nullable<System.DateTime> TiempoStamp
		{
			get
			{
				return this._TiempoStamp;
			}
			set
			{
				if ((this._TiempoStamp != value))
				{
					this._TiempoStamp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_debito_credito", DbType="NChar(50)")]
		public string debito_credito
		{
			get
			{
				return this._debito_credito;
			}
			set
			{
				if ((this._debito_credito != value))
				{
					this._debito_credito = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Banco", DbType="NChar(200)")]
		public string Banco
		{
			get
			{
				return this._Banco;
			}
			set
			{
				if ((this._Banco != value))
				{
					this._Banco = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Prestamos")]
	public partial class Prestamo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _Intereses;
		
		private System.Nullable<System.DateTime> _FechaApertura;
		
		private System.Data.Linq.Binary _HoraApertura;
		
		private System.Nullable<int> _FechaPlazo;
		
		private System.Nullable<int> _CuentaRelacionada;
		
		private EntityRef<Cuenta> _Cuenta;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnInteresesChanging(System.Nullable<int> value);
    partial void OnInteresesChanged();
    partial void OnFechaAperturaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaAperturaChanged();
    partial void OnHoraAperturaChanging(System.Data.Linq.Binary value);
    partial void OnHoraAperturaChanged();
    partial void OnFechaPlazoChanging(System.Nullable<int> value);
    partial void OnFechaPlazoChanged();
    partial void OnCuentaRelacionadaChanging(System.Nullable<int> value);
    partial void OnCuentaRelacionadaChanged();
    #endregion
		
		public Prestamo()
		{
			this._Cuenta = default(EntityRef<Cuenta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Intereses", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> Intereses
		{
			get
			{
				return this._Intereses;
			}
			set
			{
				if ((this._Intereses != value))
				{
					this.OnInteresesChanging(value);
					this.SendPropertyChanging();
					this._Intereses = value;
					this.SendPropertyChanged("Intereses");
					this.OnInteresesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaApertura", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> FechaApertura
		{
			get
			{
				return this._FechaApertura;
			}
			set
			{
				if ((this._FechaApertura != value))
				{
					this.OnFechaAperturaChanging(value);
					this.SendPropertyChanging();
					this._FechaApertura = value;
					this.SendPropertyChanged("FechaApertura");
					this.OnFechaAperturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoraApertura", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary HoraApertura
		{
			get
			{
				return this._HoraApertura;
			}
			set
			{
				if ((this._HoraApertura != value))
				{
					this.OnHoraAperturaChanging(value);
					this.SendPropertyChanging();
					this._HoraApertura = value;
					this.SendPropertyChanged("HoraApertura");
					this.OnHoraAperturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaPlazo", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> FechaPlazo
		{
			get
			{
				return this._FechaPlazo;
			}
			set
			{
				if ((this._FechaPlazo != value))
				{
					this.OnFechaPlazoChanging(value);
					this.SendPropertyChanging();
					this._FechaPlazo = value;
					this.SendPropertyChanged("FechaPlazo");
					this.OnFechaPlazoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuentaRelacionada", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> CuentaRelacionada
		{
			get
			{
				return this._CuentaRelacionada;
			}
			set
			{
				if ((this._CuentaRelacionada != value))
				{
					if (this._Cuenta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCuentaRelacionadaChanging(value);
					this.SendPropertyChanging();
					this._CuentaRelacionada = value;
					this.SendPropertyChanged("CuentaRelacionada");
					this.OnCuentaRelacionadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cuenta_Prestamo", Storage="_Cuenta", ThisKey="CuentaRelacionada", OtherKey="ID", IsForeignKey=true)]
		public Cuenta Cuenta
		{
			get
			{
				return this._Cuenta.Entity;
			}
			set
			{
				Cuenta previousValue = this._Cuenta.Entity;
				if (((previousValue != value) 
							|| (this._Cuenta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cuenta.Entity = null;
						previousValue.Prestamos.Remove(this);
					}
					this._Cuenta.Entity = value;
					if ((value != null))
					{
						value.Prestamos.Add(this);
						this._CuentaRelacionada = value.ID;
					}
					else
					{
						this._CuentaRelacionada = default(Nullable<int>);
					}
					this.SendPropertyChanged("Cuenta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
