<?xml version="1.0" encoding="utf-8"?><Database Name="CoreDB" Class="DBmodelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=Desktop-8N4FPLI;Initial Catalog=CoreDB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CoreDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Clientes" Member="Clientes">
    <Type Name="Cliente">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Apellido" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Ciudad" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Pais" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TelefonoResidencial" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TelefonoCelular" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="FechaCreacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Sexo" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="CedulaIdentidad" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="Cliente_Cuenta" Member="Cuentas" ThisKey="ID" OtherKey="IdCuenta" Type="Cuenta" />
    </Type>
  </Table>
  <Table Name="dbo.Cuentas" Member="Cuentas">
    <Type Name="Cuenta">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NumeroDeCuenta" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Tipo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Propietario" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Saldo" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TasaInteres" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IdCuenta" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Cuenta_Prestamo" Member="Prestamos" ThisKey="ID" OtherKey="CuentaRelacionada" Type="Prestamo" />
      <Association Name="Cliente_Cuenta" Member="Cliente" ThisKey="IdCuenta" OtherKey="ID" Type="Cliente" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Movimientos" Member="Movimientos">
    <Type Name="Movimiento">
      <Column Name="idMovimiento" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tipoMovimiento" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="Monto" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CuentaEmisor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CuentaReceptor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TiempoStamp" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="debito_credito" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="Banco" Type="System.String" DbType="NChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Prestamos" Member="Prestamos">
    <Type Name="Prestamo">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Intereses" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FechaApertura" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HoraApertura" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="FechaPlazo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CuentaRelacionada" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Cuenta_Prestamo" Member="Cuenta" ThisKey="CuentaRelacionada" OtherKey="ID" Type="Cuenta" IsForeignKey="true" />
    </Type>
  </Table>
</Database>