//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimiento
    {
        public int idMovimiento { get; set; }
        public string tipoMovimiento { get; set; }
        public Nullable<double> Monto { get; set; }
        public Nullable<int> CuentaEmisor { get; set; }
        public Nullable<int> CuentaReceptor { get; set; }
        public Nullable<System.DateTime> TiempoStamp { get; set; }
        public string Banco { get; set; }
    }
}
