//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamo
    {
        public int ID { get; set; }
        public Nullable<int> Intereses { get; set; }
        public Nullable<System.DateTime> FechaApertura { get; set; }
        public Nullable<System.DateTime> FechaPlazo { get; set; }
        public Nullable<int> CuentaRelacionada { get; set; }
        public Nullable<double> Monto { get; set; }
    }
}
